HTTP_STATUS_CODE_SUCCESS = 200
HTTP_STATUS_CODE_SUCCESS_CREATED = 201
HTTP_STATUS_CODE_NOT_ACCEPTABLE = 406
HTTP_STATUS_CODE_NOT_FOUND = 404
HTTP_STATUS_CODE_CONFLICT = 409

PARENT_FILENAME_NAME = "inputDatasetName"
NORMALIZATION_FILENAME_NAME = "outputDatasetName"
FIELDS_NAME = "fieldName"
NORMALIZATION_TYPE_NAME = "normalizationType"
FUNCTION_PARAMETERS_NAME = "functionParameters"
MESSAGE_RESULT = "result"
FIRST_ARGUMENT = 0

DATA_TYPE_HANDLER_HOST = "DATA_TYPE_HANDLER_HOST"
DATA_TYPE_HANDLER_PORT = "DATA_TYPE_HANDLER_PORT"

DATABASE_URL = "DATABASE_URL"
DATABASE_PORT = "DATABASE_PORT"
DATABASE_NAME = "DATABASE_NAME"
DATABASE_REPLICA_SET = "DATABASE_REPLICA_SET"

MICROSERVICE_URI_GET = "/api/learningOrchestra/v1/dataset/"
MICROSERVICE_URI_GET_PARAMS = "?query={}&limit=20&skip=0"

MESSAGE_DELETED_FILE = "deleted file"

DOCUMENT_ID_NAME = "_id"
METADATA_ID = 0
FINISHED_FIELD_NAME = "finished"
FIELD_VALUE = 1

MATRIX_ROW_INDEX = 0

NORMALIZATION_PATH = "NORMALIZATION_PATH"


